## Compute U and Q95 stats as in Racimo et al., 2017 MBE
## input files are frequency files generated by vcftools --freq
## Javier Mendoza-Revilla (javier.mendoza-revilla@pasteur.fr)

## libraries
suppressMessages(library(data.table))
suppressMessages(library(purrr))
suppressMessages(library(dplyr))
suppressMessages(library(readr))

## set args
args <- commandArgs(TRUE)
target <- as.character(args[1]) ## target human population
archaic <- as.character(args[2])  ## archaic population used to infer introgressed alleles
archaic_outgroup <- as.character(args[3]) ## second archaic population 
                                          ## to exclude shared alleles with archaic of interest
afr_outgroup <- as.character(args[4]) ## modern human without archaic ancestry (usually an African human population)
winsize <- as.numeric(args[5]) ## window size in bp e.g. 50000 as in Racimo et al. 2017
ustat_cutoff <- as.numeric(args[6]) ## allele frequency cutoff for U-statistic e.g. 0.3 or 0.5 as in Racimo et al. 2017

## load allele frequencies
target_freq <- fread(paste(target),header = F, skip = 1,stringsAsFactors = F,data.table = F)
archaic_freq <- fread(paste(archaic),header = F, skip = 1,stringsAsFactors = F,data.table = F)
archaic_outgroup_freq <- fread(paste(archaic_outgroup),header = F, skip = 1,stringsAsFactors = F,data.table = F)
afr_outgroup_freq <- fread(paste(afr_outgroup),header = F, skip = 1,stringsAsFactors = F,data.table = F)

colnames(target_freq) <- c("CHR","POS","N_ALLELES","N_CHR","REF_FREQ","ALT_FREQ")
colnames(archaic_freq) <- c("CHR","POS","N_ALLELES","N_CHR","REF_FREQ","ALT_FREQ")
colnames(archaic_outgroup_freq) <- c("CHR","POS","N_ALLELES","N_CHR","REF_FREQ","ALT_FREQ")
colnames(afr_outgroup_freq) <- c("CHR","POS","N_ALLELES","N_CHR","REF_FREQ","ALT_FREQ")

## get REF/ALT
target_freq$REF <- map(strsplit(target_freq$REF_FREQ, ":"), ~.x[1]) %>% unlist()
target_freq$ALT <- map(strsplit(target_freq$ALT_FREQ, ":"), ~.x[1]) %>% unlist()

archaic_freq$REF <- map(strsplit(archaic_freq$REF_FREQ, ":"), ~.x[1]) %>% unlist()
archaic_freq$ALT <- map(strsplit(archaic_freq$ALT_FREQ, ":"), ~.x[1]) %>% unlist()

archaic_outgroup_freq$REF <- map(strsplit(archaic_outgroup_freq$REF_FREQ, ":"), ~.x[1]) %>% unlist()
archaic_outgroup_freq$ALT <- map(strsplit(archaic_outgroup_freq$ALT_FREQ, ":"), ~.x[1]) %>% unlist()

afr_outgroup_freq$REF <- map(strsplit(afr_outgroup_freq$REF_FREQ, ":"), ~.x[1]) %>% unlist()
afr_outgroup_freq$ALT <- map(strsplit(afr_outgroup_freq$ALT_FREQ, ":"), ~.x[1]) %>% unlist()

## sort
target_freq <- target_freq[ order(target_freq[,"CHR"], target_freq[,"POS"]), ]
archaic_freq <- archaic_freq[ order(archaic_freq[,"CHR"], archaic_freq[,"POS"]), ]
archaic_outgroup_freq <- archaic_outgroup_freq[ order(archaic_outgroup_freq[,"CHR"], archaic_outgroup_freq[,"POS"]), ]
afr_outgroup_freq <- afr_outgroup_freq[ order(afr_outgroup_freq[,"CHR"], afr_outgroup_freq[,"POS"]), ]

## get allele frequencies
target_freq$REF_FREQ_NUMERIC <- as.numeric(map(strsplit(target_freq$REF_FREQ, ":"), ~.x[2]) %>% unlist())
target_freq$ALT_FREQ_NUMERIC <- as.numeric(map(strsplit(target_freq$ALT_FREQ, ":"), ~.x[2]) %>% unlist())

archaic_freq$REF_FREQ_NUMERIC <- as.numeric(map(strsplit(archaic_freq$REF_FREQ, ":"), ~.x[2]) %>% unlist())
archaic_freq$ALT_FREQ_NUMERIC <- as.numeric(map(strsplit(archaic_freq$ALT_FREQ, ":"), ~.x[2]) %>% unlist())

archaic_outgroup_freq$REF_FREQ_NUMERIC <- as.numeric(map(strsplit(archaic_outgroup_freq$REF_FREQ, ":"), ~.x[2]) %>% unlist())
archaic_outgroup_freq$ALT_FREQ_NUMERIC <- as.numeric(map(strsplit(archaic_outgroup_freq$ALT_FREQ, ":"), ~.x[2]) %>% unlist())

afr_outgroup_freq$REF_FREQ_NUMERIC <- as.numeric(map(strsplit(afr_outgroup_freq$REF_FREQ, ":"), ~.x[2]) %>% unlist())
afr_outgroup_freq$ALT_FREQ_NUMERIC <- as.numeric(map(strsplit(afr_outgroup_freq$ALT_FREQ, ":"), ~.x[2]) %>% unlist())

## REF allele MUST be the ANCESTRAL allele
## define derived allele as ALT
target_freq$DA <- target_freq$ALT
archaic_freq$DA <- archaic_freq$ALT
archaic_outgroup_freq$DA <- archaic_outgroup_freq$ALT
afr_outgroup_freq$DA <- afr_outgroup_freq$ALT

target_freq$DER_FREQ_NUMERIC <- target_freq$ALT_FREQ_NUMERIC
archaic_freq$DER_FREQ_NUMERIC <- archaic_freq$ALT_FREQ_NUMERIC
archaic_outgroup_freq$DER_FREQ_NUMERIC <- archaic_outgroup_freq$ALT_FREQ_NUMERIC
afr_outgroup_freq$DER_FREQ_NUMERIC <- afr_outgroup_freq$ALT_FREQ_NUMERIC

colnames(target_freq)[ncol(target_freq)] <- "TARGET_DER_FREQ"
colnames(archaic_freq)[ncol(archaic_freq)] <- "ARCHAIC_DER_FREQ"
colnames(archaic_outgroup_freq)[ncol(archaic_outgroup_freq)] <- "ARCHAIC_OUT_DER_FREQ"
colnames(afr_outgroup_freq)[ncol(afr_outgroup_freq)] <- "AFR_DER_FREQ"

target_freq <- target_freq[,c("CHR","POS","REF","ALT","DA","TARGET_DER_FREQ")]
archaic_freq <- archaic_freq[,c("CHR","POS","REF","ALT","DA","ARCHAIC_DER_FREQ")]
archaic_outgroup_freq <- archaic_outgroup_freq[,c("CHR","POS","REF","ALT","DA","ARCHAIC_OUT_DER_FREQ")]
afr_outgroup_freq <- afr_outgroup_freq[,c("CHR","POS","REF","ALT","DA","AFR_DER_FREQ")]

df <- left_join(target_freq,archaic_freq,by=c("CHR","POS","REF","ALT","DA"))
df <- merge(df,archaic_outgroup_freq,by=c("CHR","POS","REF","ALT","DA"))
df <- merge(df,afr_outgroup_freq,by=c("CHR","POS","REF","ALT","DA"))

## order by CHR and POS
df <- df[ order(df[,"CHR"], df[,"POS"]), ]
rm(target_freq);rm(archaic_freq);rm(archaic_outgroup_freq);rm(afr_outgroup_freq)

## compute U and Q95 statistics
## define non-overlapping windows across the chromosome
start <- seq(1,max(df$POS)+winsize*2,by=winsize)
end <- seq(winsize,max(df$POS)+winsize*2,by=winsize)
start <- start[1:length(end)]
pos <- as.data.frame(cbind(start,end))
rm(start);rm(end)

## loop through each window
dftosave <- NULL
for (i in 1:nrow(pos)){
  
  ## get win and win info
  startwin <- pos$start[i]
  endwin <- pos$end[i]
  win <- df[df$POS>=startwin & df$POS<=endwin,]
  numsnps <- nrow(win)
  
  ## get U statistics
  u_target <- win[win$AFR_DER_FREQ<0.01 & win$TARGET_DER_FREQ>ustat_cutoff & win$ARCHAIC_DER_FREQ==1 & win$ARCHAIC_OUT_DER_FREQ==0,]
  u_target <- nrow(u_target)
  
  ## get Q95 statistic
  q95_target <- win[win$AFR_DER_FREQ<0.01 & win$ARCHAIC_DER_FREQ==1 & win$ARCHAIC_OUT_DER_FREQ==0,]
  q95_target <- as.numeric(quantile(q95_target$TARGET_DER_FREQ,0.95))
  
  ## make row
  row <- c(i,startwin,endwin,numsnps,u_target,q95_target)
  
  ## add to dftosave
  dftosave <- rbind(dftosave,row)
  
  ## print statement
  # cat(paste(i,"/",nrow(pos)),"\n")
  
  
}

## save
colnames(dftosave) <- c("WINNUMBER","STARTWIN","ENDWIN","NUMSNPS","USTAT","Q95STAT")
dftosave <- as.data.frame(dftosave)
rownames(dftosave) <- NULL

## return to standard out
cat(format_tsv(dftosave,col_names = T))
